### PR TITLE
allow uploading 10x files instead of directory to work on Shiny Server

### PR DESCRIPTION
**Pull request by anhvo711**

### CODE REVIEW

**Comment by qinzhu** [comment]
Thanks @anhvo711 !

**Comment by eturkes** [comment]
Updated the Docker container

**Comment by Cala3len** [comment]
Hi !

The barcode input filename is not the same in the UI and the server. (Missing the S in the server side).

But even fixing it I got the following error after submtiting my 10Xfiles :

Error detected: Error in slot(template, slot_name): aucun slot de nom "pipestance_path" pour cet objet de la classe "GeneBCMatrix"

Do you have any idea ?

Best wishes,
Clément

**Comment by qinzhu** [comment]
Hi,
For dealing with large scale single cell data such as 10x, I recommend using my latest tool VisCello: https://github.com/qinzhu/VisCello. PIVOT was developed before the "10x age" so may not handle the most recent version of 10x data very well.

Best,
Qin

**Pull request merged**
